name: hello world
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello step
        run: |
          echo "welcome to github-actions"
          echo "this is next shell command message"
        
